{{
    config(materialized='table')
}}
-- stg_lemeng_item.sql — 乐檬商品维 staging（新湖；一对一、只规范化不改义）
-- 分区键推断类型不合约 ⇒ 两列显式 cast；取列必须 `from read_parquet(...) r` 函数别名形态
-- （CTE 形态在 pg_duckdb 上取列即报错，见 stg_lemeng_retail_order_line.sql 头注【二】）。
-- 其余 106 列在 parquet 里已由管线按契约定型（code.sql 逐列 cast），本层不再重复 cast（与 stg_lemeng_branch 同形）。
--
-- 【前缀单点】`lemeng/dim_item` 段不写死字面量 —— 用 `dbt_project.yml` 的同源 var
--   `lemeng_item_prefix`（出处：contracts/common/lemeng.item.json 的 `layout.prefix`）。
--   分区键顺序 `["system_book","snapshot"]` 与管线的 sink `key` 逐段一致（见
--   **在用的** L0 管线 `deploy/duckle/console/pipelines/lemeng.dim.item.l0.json` 的 sink 节点；🔴 2026-09-29 改向，原指已退役的 `duckle/common/lemeng.item.json`）。
--
-- 【覆盖双账套】路径段写 `*/snapshot=**/` 而不是钉单账套 —— 商品维在 dbt 侧是**一个模型读两个
--   账套分区**（`system_book` 是**列**、不是 var）。
--
-- 列与空值性以 `contracts/common/lemeng.item.json` 为准（108 列全带，本层不加语义；**另加 dbt 注入列 `org`**）。
-- 列数构成：3 注入列 + 89 标量列 + 16 摊平列（item_department 3 / item_category 9 / item_brand 4）。
select
  r['batch_id']::varchar as batch_id,
  r['system_book']::varchar as system_book,
  {{ subject_org() }}       as org,
  r['snapshot']::date as snapshot,
  r['item_num']::varchar as item_num,
  r['item_code']::varchar as item_code,
  r['bar_code']::varchar as bar_code,
  r['pinyin']::varchar as pinyin,
  r['item_name']::varchar as item_name,
  r['spec']::varchar as spec,
  r['item_type']::varchar as item_type,
  r['item_flag_names']::varchar as item_flag_names,
  r['unit_name']::varchar as unit_name,
  r['unit_group_name']::varchar as unit_group_name,
  r['tax_code']::varchar as tax_code,
  r['valid_period']::int as valid_period,
  r['made_in']::varchar as made_in,
  r['eliminate_flag']::boolean as eliminate_flag,
  r['eliminate_at']::varchar as eliminate_at,
  r['eliminate_operator']::varchar as eliminate_operator,
  r['item_sale_cease_flag']::boolean as item_sale_cease_flag,
  r['description']::varchar as description,
  r['item_point_value']::numeric(18,8) as item_point_value,
  r['item_sale_no_store']::boolean as item_sale_no_store,
  r['item_weight_flag']::boolean as item_weight_flag,
  r['item_in_tax']::numeric(18,8) as item_in_tax,
  r['item_out_tax']::numeric(18,8) as item_out_tax,
  r['free_tax_flag']::boolean as free_tax_flag,
  r['created_at']::varchar as created_at,
  r['updated_at']::varchar as updated_at,
  r['created_by']::bigint as created_by,
  r['creator']::varchar as creator,
  r['updated_by']::bigint as updated_by,
  r['item_sequence']::int as item_sequence,
  r['deleted_flag']::boolean as deleted_flag,
  r['item_cost_mode']::varchar as item_cost_mode,
  r['item_method']::varchar as item_method,
  r['item_gross_rate']::varchar as item_gross_rate,
  r['item_direct_rate']::varchar as item_direct_rate,
  r['item_en_name']::varchar as item_en_name,
  r['item_note_info']::varchar as item_note_info,
  r['item_stock_cease_flag']::boolean as item_stock_cease_flag,
  r['item_status']::int as item_status,
  r['item_remind_period']::int as item_remind_period,
  r['item_transfer_day']::int as item_transfer_day,
  r['item_purchase_scope']::varchar as item_purchase_scope,
  r['item_store_place']::varchar as item_store_place,
  r['item_assist_unit']::varchar as item_assist_unit,
  r['item_assist_rate']::numeric(18,8) as item_assist_rate,
  r['item_purchase_unit']::varchar as item_purchase_unit,
  r['item_purchase_rate']::numeric(18,8) as item_purchase_rate,
  r['item_inventory_unit']::varchar as item_inventory_unit,
  r['item_inventory_rate']::numeric(18,8) as item_inventory_rate,
  r['item_transfer_unit']::varchar as item_transfer_unit,
  r['item_transfer_rate']::numeric(18,8) as item_transfer_rate,
  r['item_wholesale_unit']::varchar as item_wholesale_unit,
  r['item_wholesale_rate']::numeric(18,8) as item_wholesale_rate,
  r['item_price_tag_flag']::boolean as item_price_tag_flag,
  r['item_print_label_flag']::boolean as item_print_label_flag,
  r['item_cost_price']::numeric(18,8) as item_cost_price,
  r['item_transfer_price']::numeric(18,8) as item_transfer_price,
  r['item_transfer_fix_type']::int as item_transfer_fix_type,
  r['item_wholesale_fix_type']::int as item_wholesale_fix_type,
  r['item_fix_assist_transfer_price']::boolean as item_fix_assist_transfer_price,
  r['item_fix_assist_wholesale_price']::boolean as item_fix_assist_wholesale_price,
  r['item_wholesale_price']::numeric(18,8) as item_wholesale_price,
  r['item_level2_wholesale']::numeric(18,8) as item_level2_wholesale,
  r['item_level3_wholesale']::numeric(18,8) as item_level3_wholesale,
  r['item_level4_wholesale']::numeric(18,8) as item_level4_wholesale,
  r['item_transfer_gross']::numeric(18,8) as item_transfer_gross,
  r['item_transfer_fixed_gross']::boolean as item_transfer_fixed_gross,
  r['item_wholesale_gross']::numeric(18,8) as item_wholesale_gross,
  r['item_wholesale_fixed_gross']::boolean as item_wholesale_fixed_gross,
  r['item_wholesale_gross2']::numeric(18,8) as item_wholesale_gross2,
  r['item_wholesale_gross3']::numeric(18,8) as item_wholesale_gross3,
  r['item_wholesale_gross4']::numeric(18,8) as item_wholesale_gross4,
  r['item_wholesale_fixed_gross2']::boolean as item_wholesale_fixed_gross2,
  r['item_wholesale_fixed_gross3']::boolean as item_wholesale_fixed_gross3,
  r['item_wholesale_fixed_gross4']::boolean as item_wholesale_fixed_gross4,
  r['item_wholesale_fix_type2']::int as item_wholesale_fix_type2,
  r['item_wholesale_fix_type3']::int as item_wholesale_fix_type3,
  r['item_wholesale_fix_type4']::int as item_wholesale_fix_type4,
  r['item_manufacture_flag']::boolean as item_manufacture_flag,
  r['item_need_product_date']::boolean as item_need_product_date,
  r['item_price_adj']::int as item_price_adj,
  r['item_transfer_return_flag']::boolean as item_transfer_return_flag,
  r['no_stock_no_request']::boolean as no_stock_no_request,
  r['item_fix_assist_cost_price']::boolean as item_fix_assist_cost_price,
  r['test_market_end_date']::varchar as test_market_end_date,
  r['new_crease']::varchar as new_crease,
  r['request_not_over_center_stock']::boolean as request_not_over_center_stock,
  r['material_url']::varchar as material_url,
  r['wholesale_book_allow_over_center_stock']::boolean as wholesale_book_allow_over_center_stock,
  r['item_department_id']::bigint as item_department_id,
  r['item_department_name']::varchar as item_department_name,
  r['item_department_code']::varchar as item_department_code,
  r['item_category_code']::varchar as item_category_code,
  r['item_category_en_name']::varchar as item_category_en_name,
  r['item_category_name']::varchar as item_category_name,
  r['item_category_id']::bigint as item_category_id,
  r['item_category_level']::int as item_category_level,
  r['item_category_parent_id']::bigint as item_category_parent_id,
  r['item_category_pinyin']::varchar as item_category_pinyin,
  r['item_category_sort']::int as item_category_sort,
  r['item_category_tax_code']::varchar as item_category_tax_code,
  r['item_brand_code']::varchar as item_brand_code,
  r['item_brand_name']::varchar as item_brand_name,
  r['item_brand_pinyin']::varchar as item_brand_pinyin,
  r['item_brand_id']::bigint as item_brand_id
from read_parquet(
  's3://{{ var("zos_bucket") }}/{{ var("lemeng_item_prefix") }}/*/snapshot=**/all.parquet'
) r
