{{
    config(materialized='table')
}}
-- stg_lemeng_item.sql — 乐檬商品维 staging（新湖；一对一、只规范化不改义）
-- 分区键推断类型不合约 ⇒ 两列显式 cast；取列必须 `from read_parquet(...) r` 函数别名形态
-- （CTE 形态在 pg_duckdb 上取列即报错，见 stg_lemeng_retail_order_line.sql 头注【二】）。
-- 其余 106 列在 parquet 里已由管线按契约定型（code.sql 逐列 cast），本层不再重复 cast（与 stg_lemeng_branch 同形）。
--
-- 【前缀单点】`lemeng/dim_item` 段不写死字面量 —— 用 `dbt_project.yml` 的同源 var
--   `lemeng_item_prefix`（出处：contracts/common/lemeng.item.json 的 `layout.prefix`）。
--   分区键顺序 `["system_book","snapshot"]` 与管线的 sink `key` 逐段一致（见
--   duckle/common/lemeng.item.json 的 sink 节点）。
--
-- 【覆盖双账套】路径段写 `*/snapshot=**/` 而不是钉单账套 —— 商品维在 dbt 侧是**一个模型读两个
--   账套分区**（`system_book` 是**列**、不是 var）。
--
-- 列与空值性以 `contracts/common/lemeng.item.json` 为准（108 列全带，本层不加语义；**另加 dbt 注入列 `org`**）。
-- 列数构成：3 注入列 + 89 标量列 + 16 摊平列（item_department 3 / item_category 9 / item_brand 4）。
select
  r['batch_id'] as batch_id,
  r['system_book']::varchar as system_book,
  {{ subject_org() }} as org,
  r['snapshot']::date as snapshot,
  r['item_num'] as item_num,
  r['item_code'] as item_code,
  r['bar_code'] as bar_code,
  r['pinyin'] as pinyin,
  r['item_name'] as item_name,
  r['spec'] as spec,
  r['item_type'] as item_type,
  r['item_flag_names'] as item_flag_names,
  r['unit_name'] as unit_name,
  r['unit_group_name'] as unit_group_name,
  r['tax_code'] as tax_code,
  r['valid_period'] as valid_period,
  r['made_in'] as made_in,
  r['eliminate_flag'] as eliminate_flag,
  r['eliminate_at'] as eliminate_at,
  r['eliminate_operator'] as eliminate_operator,
  r['item_sale_cease_flag'] as item_sale_cease_flag,
  r['description'] as description,
  r['item_point_value'] as item_point_value,
  r['item_sale_no_store'] as item_sale_no_store,
  r['item_weight_flag'] as item_weight_flag,
  r['item_in_tax'] as item_in_tax,
  r['item_out_tax'] as item_out_tax,
  r['free_tax_flag'] as free_tax_flag,
  r['created_at'] as created_at,
  r['updated_at'] as updated_at,
  r['created_by'] as created_by,
  r['creator'] as creator,
  r['updated_by'] as updated_by,
  r['item_sequence'] as item_sequence,
  r['deleted_flag'] as deleted_flag,
  r['item_cost_mode'] as item_cost_mode,
  r['item_method'] as item_method,
  r['item_gross_rate'] as item_gross_rate,
  r['item_direct_rate'] as item_direct_rate,
  r['item_en_name'] as item_en_name,
  r['item_note_info'] as item_note_info,
  r['item_stock_cease_flag'] as item_stock_cease_flag,
  r['item_status'] as item_status,
  r['item_remind_period'] as item_remind_period,
  r['item_transfer_day'] as item_transfer_day,
  r['item_purchase_scope'] as item_purchase_scope,
  r['item_store_place'] as item_store_place,
  r['item_assist_unit'] as item_assist_unit,
  r['item_assist_rate'] as item_assist_rate,
  r['item_purchase_unit'] as item_purchase_unit,
  r['item_purchase_rate'] as item_purchase_rate,
  r['item_inventory_unit'] as item_inventory_unit,
  r['item_inventory_rate'] as item_inventory_rate,
  r['item_transfer_unit'] as item_transfer_unit,
  r['item_transfer_rate'] as item_transfer_rate,
  r['item_wholesale_unit'] as item_wholesale_unit,
  r['item_wholesale_rate'] as item_wholesale_rate,
  r['item_price_tag_flag'] as item_price_tag_flag,
  r['item_print_label_flag'] as item_print_label_flag,
  r['item_cost_price'] as item_cost_price,
  r['item_transfer_price'] as item_transfer_price,
  r['item_transfer_fix_type'] as item_transfer_fix_type,
  r['item_wholesale_fix_type'] as item_wholesale_fix_type,
  r['item_fix_assist_transfer_price'] as item_fix_assist_transfer_price,
  r['item_fix_assist_wholesale_price'] as item_fix_assist_wholesale_price,
  r['item_wholesale_price'] as item_wholesale_price,
  r['item_level2_wholesale'] as item_level2_wholesale,
  r['item_level3_wholesale'] as item_level3_wholesale,
  r['item_level4_wholesale'] as item_level4_wholesale,
  r['item_transfer_gross'] as item_transfer_gross,
  r['item_transfer_fixed_gross'] as item_transfer_fixed_gross,
  r['item_wholesale_gross'] as item_wholesale_gross,
  r['item_wholesale_fixed_gross'] as item_wholesale_fixed_gross,
  r['item_wholesale_gross2'] as item_wholesale_gross2,
  r['item_wholesale_gross3'] as item_wholesale_gross3,
  r['item_wholesale_gross4'] as item_wholesale_gross4,
  r['item_wholesale_fixed_gross2'] as item_wholesale_fixed_gross2,
  r['item_wholesale_fixed_gross3'] as item_wholesale_fixed_gross3,
  r['item_wholesale_fixed_gross4'] as item_wholesale_fixed_gross4,
  r['item_wholesale_fix_type2'] as item_wholesale_fix_type2,
  r['item_wholesale_fix_type3'] as item_wholesale_fix_type3,
  r['item_wholesale_fix_type4'] as item_wholesale_fix_type4,
  r['item_manufacture_flag'] as item_manufacture_flag,
  r['item_need_product_date'] as item_need_product_date,
  r['item_price_adj'] as item_price_adj,
  r['item_transfer_return_flag'] as item_transfer_return_flag,
  r['no_stock_no_request'] as no_stock_no_request,
  r['item_fix_assist_cost_price'] as item_fix_assist_cost_price,
  r['test_market_end_date'] as test_market_end_date,
  r['new_crease'] as new_crease,
  r['request_not_over_center_stock'] as request_not_over_center_stock,
  r['material_url'] as material_url,
  r['wholesale_book_allow_over_center_stock'] as wholesale_book_allow_over_center_stock,
  r['item_department_id'] as item_department_id,
  r['item_department_name'] as item_department_name,
  r['item_department_code'] as item_department_code,
  r['item_category_code'] as item_category_code,
  r['item_category_en_name'] as item_category_en_name,
  r['item_category_name'] as item_category_name,
  r['item_category_id'] as item_category_id,
  r['item_category_level'] as item_category_level,
  r['item_category_parent_id'] as item_category_parent_id,
  r['item_category_pinyin'] as item_category_pinyin,
  r['item_category_sort'] as item_category_sort,
  r['item_category_tax_code'] as item_category_tax_code,
  r['item_brand_code'] as item_brand_code,
  r['item_brand_name'] as item_brand_name,
  r['item_brand_pinyin'] as item_brand_pinyin,
  r['item_brand_id'] as item_brand_id
from read_parquet(
  's3://{{ var("zos_bucket") }}/{{ var("lemeng_item_prefix") }}/*/snapshot=**/all.parquet'
) r
